In [1]:
import torch
import numpy as np

In [3]:
t1=torch.Tensor([1,2,3])

In [4]:
t1

tensor([1., 2., 3.])

In [7]:
torch.Tensor(np.array([[1,2,3],[4,5,6]]))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
torch.empty(3,4)#创建为空

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
torch.randint(3,10,(2,2))

tensor([[8, 5],
        [5, 8]])

In [13]:
torch.randint(3,10,(2,2))

tensor([[5, 6],
        [8, 7]])

In [14]:
torch.rand(2,6) #0-1内随机数

tensor([[0.9910, 0.8917, 0.7378, 0.3367, 0.3725, 0.8654],
        [0.5964, 0.9389, 0.7839, 0.9473, 0.1457, 0.0557]])

In [17]:
torch.randn(2,6)#标准正太随机列

tensor([[ 0.5594,  0.1604, -1.1875,  0.6879, -1.1340,  0.6274],
        [ 0.0519, -0.8568, -0.3399, -0.4667, -0.5630, -0.4345]])

In [21]:
torch.normal(5,15,[5,4]) #创建无行四列正态分布

tensor([[ 10.4754,  -4.7029,  -4.6343,   8.3027],
        [-24.7683,  37.5556, -18.5078,   1.3415],
        [ 23.3185,  23.6644,   5.0529,  -5.5292],
        [ 13.6941,  30.8173,  13.9593,  -2.5306],
        [  1.3434,  26.0175,  19.4721,   8.6255]])

In [22]:
torch.linspace(1,15,20)

tensor([ 1.0000,  1.7368,  2.4737,  3.2105,  3.9474,  4.6842,  5.4211,  6.1579,
         6.8947,  7.6316,  8.3684,  9.1053,  9.8421, 10.5789, 11.3158, 12.0526,
        12.7895, 13.5263, 14.2632, 15.0000])

In [24]:
torch.logspace(1,15,20,base=2)

tensor([2.0000e+00, 3.3330e+00, 5.5546e+00, 9.2569e+00, 1.5427e+01, 2.5709e+01,
        4.2845e+01, 7.1402e+01, 1.1899e+02, 1.9831e+02, 3.3048e+02, 5.5075e+02,
        9.1784e+02, 1.5296e+03, 2.5491e+03, 4.2482e+03, 7.0797e+03, 1.1798e+04,
        1.9662e+04, 3.2768e+04])

In [25]:
t2=torch.normal(5,15,[5,4]) #创建无行四列正态分布

In [29]:
t3=t2.numpy()

In [30]:
t3

array([[ 33.073544 ,  17.293966 , -14.636245 ,  12.233781 ],
       [  2.5425477,  18.73514  ,  10.974526 ,   7.0064826],
       [ 26.77571  ,  24.791906 ,  10.144696 ,   8.030356 ],
       [  5.472688 ,   6.529416 ,  17.026323 ,  -8.363294 ],
       [ -0.3548394,  15.964835 , -28.753576 ,  -1.6570134]],
      dtype=float32)

In [33]:
t4=torch.Tensor([[[1]]])

In [34]:
t4

tensor([[[1.]]])

In [35]:
t4.item()#得到一个元素的值，如果矩阵或者数组有多个值报错

1.0

In [37]:
t5=torch.Tensor([[[1,2]]])
t5.item()

ValueError: only one element tensors can be converted to Python scalars

In [38]:
t5.numpy()

array([[[1., 2.]]], dtype=float32)

In [39]:
t5.size()

torch.Size([1, 1, 2])

In [41]:
t5.size(0)

1

In [40]:
t5.size(2)#第二个列的形状

2

In [51]:
t2

tensor([[ 33.0735,  17.2940, -14.6362,  12.2338],
        [  2.5425,  18.7351,  10.9745,   7.0065],
        [ 26.7757,  24.7919,  10.1447,   8.0304],
        [  5.4727,   6.5294,  17.0263,  -8.3633],
        [ -0.3548,  15.9648, -28.7536,  -1.6570]])

In [52]:
t2.view(4,5)

tensor([[ 33.0735,  17.2940, -14.6362,  12.2338,   2.5425],
        [ 18.7351,  10.9745,   7.0065,  26.7757,  24.7919],
        [ 10.1447,   8.0304,   5.4727,   6.5294,  17.0263],
        [ -8.3633,  -0.3548,  15.9648, -28.7536,  -1.6570]])

In [53]:
t2.dim()

2

In [54]:
t2.t()#转置

tensor([[ 33.0735,   2.5425,  26.7757,   5.4727,  -0.3548],
        [ 17.2940,  18.7351,  24.7919,   6.5294,  15.9648],
        [-14.6362,  10.9745,  10.1447,  17.0263, -28.7536],
        [ 12.2338,   7.0065,   8.0304,  -8.3633,  -1.6570]])

In [57]:
t6=torch.Tensor(np.arange(24).reshape(2,3,4))

In [60]:
t6

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [61]:
t6.size()

torch.Size([2, 3, 4])

In [64]:
t6.transpose(0,1) #shape第一个值和第二个值交换

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [65]:
t6.permute(2,1,0) #shape交换后的位置

tensor([[[ 0., 12.],
         [ 4., 16.],
         [ 8., 20.]],

        [[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]]])

In [66]:
t6.permute(0,1,2)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [69]:
# Tensor会设定默认格式
t7=torch.Tensor(np.arange(12,dtype=np.int32))

In [89]:
torch.Tensor(np.arange(12),dtype=torch.int32) #因为违背默认格式则报错

TypeError: new() received an invalid combination of arguments - got (numpy.ndarray, dtype=torch.dtype), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [70]:
t7.dtype

torch.float32

In [71]:
t7.int()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

In [72]:
#tensor不会
t8=torch.tensor(np.arange(12,dtype=np.int32))

In [73]:
t8.dtype

torch.int32

In [88]:
# DoubleTensor会设定默认格式
torch.DoubleTensor(np.arange(12,dtype=np.int32)).dtype

torch.float64

In [86]:
torch.ones(3,4,dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [11]:
x=torch.Tensor(np.array([[1,2,3],[4,5,6]]))

In [12]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x = x.new_ones(5,3,dtype=torch.float)

In [14]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
y = torch.rand(5,3)

In [16]:
y

tensor([[0.3689, 0.0233, 0.4009],
        [0.3730, 0.7473, 0.0390],
        [0.3989, 0.9179, 0.3989],
        [0.5739, 0.8360, 0.4235],
        [0.0602, 0.5865, 0.1433]])

In [17]:
x+y

tensor([[1.3689, 1.0233, 1.4009],
        [1.3730, 1.7473, 1.0390],
        [1.3989, 1.9179, 1.3989],
        [1.5739, 1.8360, 1.4235],
        [1.0602, 1.5865, 1.1433]])

In [18]:
torch.add(x,y)

tensor([[1.3689, 1.0233, 1.4009],
        [1.3730, 1.7473, 1.0390],
        [1.3989, 1.9179, 1.3989],
        [1.5739, 1.8360, 1.4235],
        [1.0602, 1.5865, 1.1433]])

In [19]:
x.add(y)

tensor([[1.3689, 1.0233, 1.4009],
        [1.3730, 1.7473, 1.0390],
        [1.3989, 1.9179, 1.3989],
        [1.5739, 1.8360, 1.4235],
        [1.0602, 1.5865, 1.1433]])

In [21]:
x.add_(y) #改变x的值

tensor([[1.3689, 1.0233, 1.4009],
        [1.3730, 1.7473, 1.0390],
        [1.3989, 1.9179, 1.3989],
        [1.5739, 1.8360, 1.4235],
        [1.0602, 1.5865, 1.1433]])

In [22]:
x

tensor([[1.3689, 1.0233, 1.4009],
        [1.3730, 1.7473, 1.0390],
        [1.3989, 1.9179, 1.3989],
        [1.5739, 1.8360, 1.4235],
        [1.0602, 1.5865, 1.1433]])

In [26]:
x.transpose_(0,1)

tensor([[1.3689, 1.3730, 1.3989, 1.5739, 1.0602],
        [1.0233, 1.7473, 1.9179, 1.8360, 1.5865],
        [1.4009, 1.0390, 1.3989, 1.4235, 1.1433]])

In [27]:
x

tensor([[1.3689, 1.3730, 1.3989, 1.5739, 1.0602],
        [1.0233, 1.7473, 1.9179, 1.8360, 1.5865],
        [1.4009, 1.0390, 1.3989, 1.4235, 1.1433]])

In [28]:
torch.cuda.is_available() #此电脑支持gpu跑代码

True

In [29]:
device = torch.device("cuda") #cuda device对象即用gpu跑代码，填入"cpu"就是cpu跑代码

In [34]:
device

device(type='cuda')

In [30]:
y = torch.ones_like(x,device=device)#ones 创建gpu的类似于cpu的tensor格式x的x

In [31]:
x=x.to(device)                     #将cpu的tensor 变为gpu的,直接变

In [32]:
z=x+y

In [33]:
print(z)

tensor([[2.3689, 2.3730, 2.3989, 2.5739, 2.0602],
        [2.0233, 2.7473, 2.9179, 2.8360, 2.5865],
        [2.4009, 2.0390, 2.3989, 2.4235, 2.1433]], device='cuda:0')


In [37]:
torch.ones(5,3).device  #默认cpu，需要设置device='cuda'

device(type='cpu')

In [38]:
k=torch.ones(3,5)

In [39]:
k+z #因为device不同不能加

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [43]:
torch.ones(3,5,device='cuda')+z

tensor([[3.3689, 3.3730, 3.3989, 3.5739, 3.0602],
        [3.0233, 3.7473, 3.9179, 3.8360, 3.5865],
        [3.4009, 3.0390, 3.3989, 3.4235, 3.1433]], device='cuda:0')